version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/segurado!
      - public-data:/segurado!/public
      - tmp-data:/segurado!/tmp
      - log-data:/segurado!/log
    depends_on:
      - db
  db:
    image: mysql:5.7
    env_file:
      - ./.env
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/segurado!/public
      - tmp-data:/segurado!/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: