version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: ymmtyk28
      MYSQL_DATABASE: segurado!_db
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "4306:3306"

  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/segurado!
      - public-data:/segurado!/public
      - tmp-data:/segurado!/tmp
      - log-data:/segurado!/log

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/segurado!/public
      - tmp-data:/segurado!/tmp
    ports:
      - 80:80

volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data: