version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Docker/rails/dockerfile
    command: bundle exec puma -c config/puma.rb
    volumes:
      - .:segurado
      - public-data:/webapp/public
      - tmp-data:/segurado/tmp
      - log-data:/segurado/log
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: ./Docker/mysql/Dockerfile
    environment:
    volums:
      - db-data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: ./Docker/nginx/Dockerfile
    volums:
      - public-data:segurado/public
      - tmp-data:/segurado/tmp
    ports:
      - 80:80
    depends_on:
      - app